[package]
name = "chacha20poly"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
checkct = { path = "../checkct" }
chacha20poly1305 = { version = "0.10.1", default_features = false, features = ["rand_core", "heapless", "reduced-round"] }
