//----- AUTOGENERATED BY CARGO-CHECKCT: DO NOT MODIFY -----
//
//! `PrivateRng` produces secret values, and `PublicRng` produces public values.
//! Both provide `next_u32`, `next_u64` and `fill_bytes` methods, and implement
//! the traits of rand_core 0.10, 0.9 and 0.6.
#![allow(dead_code)]

#[unsafe(no_mangle)]
#[inline(never)]
pub fn __checkct_private_rand() -> u8 {
    unsafe { core::ptr::read_volatile(0xcafe as *const u8) }
}

#[unsafe(no_mangle)]
#[inline(never)]
pub fn __checkct_public_rand() -> u8 {
    unsafe { core::ptr::read_volatile(0xf00d as *const u8) }
}

#[allow(unused_imports)]
pub use rand_core::{CryptoRng, Rng};
// Drivers generated by older versions of cargo-checkct import `RngCore`
#[allow(unused_imports)]
pub use rand_core_06::RngCore;

pub struct PrivateRng;
pub struct PublicRng;

macro_rules! impl_rng {
    ($rng:ident, $rand:ident) => {
        impl $rng {
            pub const fn new() -> Self {
                Self
            }

            pub fn next_u32(&mut self) -> u32 {
                u32::from_be_bytes([$rand(), $rand(), $rand(), $rand()])
            }

            pub fn next_u64(&mut self) -> u64 {
                (self.next_u32() as u64) << 32 | (self.next_u32() as u64)
            }

            pub fn fill_bytes(&mut self, dest: &mut [u8]) {
                for d in dest {
                    *d = $rand();
                }
            }
        }

        impl rand_core::TryRng for $rng {
            type Error = core::convert::Infallible;

            fn try_next_u32(&mut self) -> Result<u32, Self::Error> {
                Ok($rng::next_u32(self))
            }

            fn try_next_u64(&mut self) -> Result<u64, Self::Error> {
                Ok($rng::next_u64(self))
            }

            fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), Self::Error> {
                $rng::fill_bytes(self, dest);
                Ok(())
            }
        }

        impl rand_core::TryCryptoRng for $rng {}

        impl rand_core_09::RngCore for $rng {
            fn next_u32(&mut self) -> u32 {
                $rng::next_u32(self)
            }

            fn next_u64(&mut self) -> u64 {
                $rng::next_u64(self)
            }

            fn fill_bytes(&mut self, dest: &mut [u8]) {
                $rng::fill_bytes(self, dest)
            }
        }

        impl rand_core_09::CryptoRng for $rng {}

        impl rand_core_06::RngCore for $rng {
            fn next_u32(&mut self) -> u32 {
                $rng::next_u32(self)
            }

            fn next_u64(&mut self) -> u64 {
                $rng::next_u64(self)
            }

            fn fill_bytes(&mut self, dest: &mut [u8]) {
                $rng::fill_bytes(self, dest)
            }

            fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), rand_core_06::Error> {
                $rng::fill_bytes(self, dest);
                Ok(())
            }
        }

        impl rand_core_06::CryptoRng for $rng {}
    };
}

impl_rng!(PrivateRng, __checkct_private_rand);
impl_rng!(PublicRng, __checkct_public_rand);
