[package]
name = "chachapoly"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
chacha20poly1305 = { version = "0.10.1", default-features = false, features = ["rand_core", "heapless", "reduced-round"] }
