#![no_std]
#![no_main]
        
#[no_mangle]
#[inline(never)]
fn __checkct() {
    // USER CODE GOES HERE
    let mut key = [0u8; 16];
    let mut block = [0u8; 16];
    PrivateRng.fill_bytes(&mut key);
    PublicRng.fill_bytes(&mut block);
    let mut aes = masked_aes::MaskedAes::new(key, PrivateRng.next_u32());
    core::hint::black_box(aes.encrypt(block));
}


//----- AUTOGENERATED BY CHECKCT: DO NOT MODIFY -----
//
mod rng;
use rng::*;

#[no_mangle]
pub extern "C" fn _start() -> ! {
    core::hint::black_box(__checkct());
    panic!()
}
        
#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}