[build]
target = ["x86_64-unknown-linux-gnu"]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"

[unstable]
unstable-options = true
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort", "compiler-builtins-mem"]
