# [build]
# target = "thumbv7em-none-eabihf", "riscv32imac-unknown-none-elf", "x86_64-unknown-linux-gnu"]

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.thumbv7em-none-eabihf]
runner = "binsec -sse -checkct -sse-depth 1000000000 -sse-jump-enum 64 -sse-script target/thumbv7em-none-eabihf/driver.binsec -sse-timeout 600 -arm-supported-modes thumb"

[target.riscv32imac-unknown-none-elf]
runner = "binsec -sse -checkct -sse-depth 1000000000 -sse-jump-enum 64 -sse-script target/riscv32imac-unknown-none-elf/driver.binsec -sse-timeout 600"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "relocation-model=static"]
runner = "binsec -sse -checkct -sse-depth 1000000000 -sse-jump-enum 64 -sse-script target/x86_64-unknown-linux-gnu/driver.binsec -sse-timeout 600"

[unstable]
# unstable-options = true
build-std = ["core", "panic_abort"]
build-std-features = ["panic_immediate_abort", "compiler-builtins-mem"]
