name: lint

on:
  pull_request:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rustup
        run: |
          rustup update --no-self-update nightly
          rustup component add --toolchain nightly rustfmt clippy
          rustup default nightly
      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --verbose