name: lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: rustup
        run: rustup component add rustfmt clippy
      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: |
          cargo clippy --verbose --all-targets -p cargo-checkct
          cargo clippy --verbose -p checkct_macros
