name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.3
      - name: rustup
        run: |
          rustup update --no-self-update nightly
          rustup component add --toolchain nightly rust-src
          rustup default nightly
      - name: install binsec
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev gcc g++ opam
          opam init -y
          opam install -y dune dune-site menhir grain_dypgen ocamlgraph zarith toml bitwuzla
          eval $(opam env)
          git clone --branch 0.9.1 https://github.com/binsec/binsec
          git clone --branch 0.0.8 https://github.com/binsec/unisim_archisec
          pushd unisim_archisec && git apply ../unisim.patch && dune build @install && dune install && popd
          pushd binsec && dune build @install && dune install && popd
      - name: run tests
        run: eval $(opam env) && cargo test
